# Generated by Django 4.2.3 on 2023-07-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sub", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="app.categoryphoto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="photos", to="app.categoryphoto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sub", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="app.categoryblog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("source", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateTimeField()),
                ("poster", models.CharField(max_length=50, null=True)),
                (
                    "category",
                    models.ManyToManyField(related_name="blog", to="app.categoryblog"),
                ),
            ],
        ),
    ]
