# Generated by Django 4.2.3 on 2023-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_group", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("year", models.CharField(max_length=100)),
                ("social_network", models.CharField(max_length=100)),
                ("intro", models.TextField(max_length=100)),
                ("achier", models.CharField(max_length=100)),
            ],
        ),
    ]
