# Generated by Django 4.2.3 on 2023-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_photos_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="stt",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
