# Generated by Django 4.2.3 on 2023-07-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_blog_stt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
