# Generated by Django 4.2.3 on 2023-07-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntroEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("intro", models.TextField()),
                ("dates", models.DateField()),
                ("address", models.CharField(max_length=500, null=True)),
                ("times", models.TimeField()),
            ],
        ),
    ]
