# Generated by Django 4.2.3 on 2023-07-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_introfederation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("statute", models.CharField(max_length=100)),
                ("intro", models.TextField(max_length=100)),
                ("law", models.CharField(max_length=100)),
            ],
        ),
    ]
