# Generated by Django 4.2.3 on 2023-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_photo_category_photo_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=10)),
                ("password1", models.CharField(max_length=20)),
                ("password2", models.CharField(max_length=20)),
            ],
        ),
    ]
