# Generated by Django 4.2.3 on 2023-07-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
