# Generated by Django 4.2.3 on 2023-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_athlete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="sex",
            field=models.CharField(max_length=5),
        ),
    ]
