# Generated by Django 4.2.3 on 2023-07-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_customer_delete_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
    ]
