# Generated by Django 4.2.3 on 2023-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_athlete_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="fullname",
            field=models.CharField(max_length=200),
        ),
    ]
