# Generated by Django 4.2.3 on 2023-07-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_referee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="archie",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coach",
            name="archie",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referee",
            name="archie",
            field=models.TextField(max_length=100),
        ),
    ]
