# Generated by Django 4.2.3 on 2023-07-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_athlete_archie_alter_coach_archie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("create_at", models.DateField()),
                ("tag", models.CharField(max_length=1000, null=True)),
                (
                    "uploaded_file",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
