# Generated by Django 4.2.3 on 2023-07-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_library"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Library",
            new_name="LibraryText",
        ),
    ]
