# Generated by Django 4.2.3 on 2023-07-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_introevolution_intromission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
            ],
        ),
    ]
